name: Build and Deploy to AWS

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.x'  

      - name: Build project  
        run: |
          cd CecarChifferApi  
          dotnet restore
          dotnet publish -c Release -o site

      - name: Debug information
        run: ls -R

      - name: Create ZIP package
        run: |
          cd CecarChifferApi/site  
          zip -r ../../site.zip *

      - name: Verify ZIP
        run: unzip -l site.zip
          

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          application_name: cecar-chiffer
          environment_name: Cecar-chiffer-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip